version: '3.8'

services:
  taskify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskify-app
    ports:
      - "80:80"  # Changed from 8080:80 to 80:80 for direct access
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    restart: unless-stopped
    networks:
      - taskify-network
    # Added healthcheck
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  taskify-network:
    driver: bridge